// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Book Recommendation ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Book Recommendation ', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1302, height: 748 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("miki@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Miki@123")
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.linkText("Recommendations")).click()
    await driver.findElement(By.id("user_input")).click()
    await driver.findElement(By.id("user_input")).sendKeys("1984")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("user_input")).click()
    await driver.findElement(By.id("user_input")).click()
    await driver.findElement(By.id("user_input")).sendKeys("Icebound")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".col")).click()
    await driver.findElement(By.id("user_input")).click()
    await driver.findElement(By.id("user_input")).sendKeys("Spider man")
    await driver.findElement(By.css(".btn")).click()
  })
})
