// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Feedback', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Feedback', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1302, height: 748 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("pahani@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Pahani2123")
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.linkText("About Us")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Pahani")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("pahani@gmail.com")
    await driver.findElement(By.id("feedback")).click()
    await driver.findElement(By.id("feedback")).sendKeys("Feedback testing. ")
    await driver.findElement(By.css(".btn")).click()
  })
})
