// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Signup', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Signup', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1302, height: 748 })
    await driver.findElement(By.linkText("Create Account")).click()
    await driver.findElement(By.id("form1")).click()
    await driver.findElement(By.id("form1")).sendKeys("Pahani Gamage")
    await driver.findElement(By.id("form2")).click()
    await driver.findElement(By.id("form2")).sendKeys("pahani@gmail.com")
    await driver.findElement(By.id("form3")).click()
    await driver.findElement(By.id("form3")).sendKeys("Pahani2123")
    await driver.findElement(By.css(".btn")).click()
  })
})
